name: Dependabot
on: pull_request
jobs:
  approve_and_comment:
    if: github.actor == 'dbrockman'
    runs-on: ubuntu-latest
    steps:
      - name: approve_and_comment
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            await github.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.number,
              event: 'APPROVE'
            });
            await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.number,
              body: '@dbrockman Great job!'
            });
