name: CI

on:
  push:
  pull_request:

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: log_info
        run: |
          echo "github.event_name: ${{ github.event_name }}"
          echo "github.actor: ${{ github.actor }}"
          echo "context.payload.pull_request.number: ${{ context.payload.pull_request.number }}"
