name: CI

on:
  push:
  pull_request:

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: log_info
        env:
          X_GITHUB_EVENT_NAME: ${{ github.event_name }}
          X_GITHUB_ACTOR: ${{ github.actor }}
          X_CONTEXT_PAYLOAD_PULL_REQUEST_NUMBER: ${{ context.payload.pull_request.number }}
        run: |
          echo "github.event_name: $X_GITHUB_EVENT_NAME"
          echo "github.actor: $X_GITHUB_ACTOR"
          echo "context.payload.pull_request.number: $X_CONTEXT_PAYLOAD_PULL_REQUEST_NUMBER"
