name: CI

on:
  push:
  pull_request:

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: log_info
        env:
          X_GITHUB_EVENT_NAME: ${{ github.event_name }}
          X_GITHUB_ACTOR: ${{ github.actor }}
          X_github_head_ref: ${{ github.head_ref }}
          X_github_base_ref: ${{ github.base_ref }}
          X_github_ref: ${{ github.ref }}
        run: |
          echo "github.event_name: $X_GITHUB_EVENT_NAME"
          echo "github.actor: $X_GITHUB_ACTOR"
          echo "github.head_ref: $X_github_head_ref"
          echo "github.base_ref: $X_github_base_ref"
          echo "github.ref: $X_github_ref"
